@endpoint=http://localhost:3002/


// create
POST {{endpoint}}api/user
Content-Type: application/json

{
  "userId": "khm0813",
  "userName": "사용자",
  "password": "1234", 
  "role": "normal"
}

#####
// findAll
curl --request GET\
  --url {{endpoint}}api/user/
  -H 'accept: */*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJraG0wODEzIiwidXNlck5hbWUiOiLsgqzsmqnsnpAiLCJzZXEiOjQsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NDcyMzg5NzEsImV4cCI6MTY0NzI0MjU3MX0.sdkTymIMYNaDPRL4-wkV_8gN60g3W_PAomV2f3Yo8w4'


#####
// findOne
GET {{endpoint}}api/user/admin


#####
POST {{endpoint}}api/auth/login
Content-Type: application/json

{
  "userId": "admin2",
  "password": "admin"
}


#####
//GET {{endpoint}}api/auth/profile
curl --request GET\
  --url {{endpoint}}api/auth/profile
  -H 'accept: */*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJraG0wODEzIiwidXNlck5hbWUiOiLsgqzsmqnsnpAiLCJzZXEiOjQsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NDcyNDE5MjEsImV4cCI6MTY0NzI0MTk4MX0.jo72I1G1EVFIGQryIvxoF1styhSeA55JyKRu3xSJ8CQ'


