@endpoint=http://localhost:3002/


// create
POST {{endpoint}}user
Content-Type: application/json

{
  "userId": "admin2",
  "userName": "관리자",
  "password": "admin",
  "role": "admin"
}

#####
// findAll
GET {{endpoint}}api/user/
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbiIsInVzZXJOYW1lIjoia2htIiwic2VxIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDcyMzM1MzAsImV4cCI6MTY0NzIzNDEzMH0.OlAH4MmSDachIG8kcxgbd0fYUmP_QLza-Pf5wFovFJM'


#####
// findOne
GET {{endpoint}}api/user/admin


#####
POST {{endpoint}}api/auth/login
Content-Type: application/json

{
  "userId": "admin",
  "password": "admin"
}


#####
//GET {{endpoint}}api/auth/profile
curl --request GET\
  --url {{endpoint}}api/auth/profile
  -H 'accept: */*' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbiIsInVzZXJOYW1lIjoia2htIiwic2VxIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDcyMzQ0ODAsImV4cCI6MTY0NzIzNTA4MH0.YLwNGhq-M9bBzWNfa_o-CmHR7aUjdyHj_pmTkaSK4dw'
