server: 
  port: 3000
  
db:
  type: 'postgres'
  port: 5432
  database: 'exam_db'
  host: '127.0.0.1'
  username: 'postgres'
  password: 'postgres'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'Secret1234'
  refresh_secret: 'Secret1234!'
  refresh_expiresIn: 360000