server: 
  port: 3000
  
db:
  type: 'postgres'
  port: 5432
  database: 'exam_db'
  host: '127.0.0.1'
<<<<<<< HEAD
  username: 'postgres'
  password: 'postgres'
=======
  username: 'sa'
  password: 'khm0813'
>>>>>>> 6c9269bae7f948e7d262b7d7c06d5fd1b3dd6650
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'Secret1234'
  refresh_secret: 'Secret1234!'
  refresh_expiresIn: 360000