server: 
  port: 3002
  
db:
  type: 'postgres'
  port: 5432
  database: 'auth_db'
  host: '127.0.0.1'
  username: 'sa'
  password: 'khm0813'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'Secret1234'
  refresh_secret: 'Secret1234!'
  refresh_expiresIn: 360000